- README.en-US.md
- README.md
> docs: 如何启动案例

- packages/li-analysis-assets/package.json
- packages/li-core-assets/package.json
- packages/li-editor/package.json
- packages/li-p2/package.json
- packages/li-sdk/package.json
> chore: update package desc

- packages/li-editor/src/widgets/UploadDataset/UploadDatasetList/index.less
> fix: 上传文件列表样式

- examples/builder/.umirc.ts
- packages/li-editor/docs/case/Extend/demos/add-dataset/CustomAddDataset/CustomAddDataset.less
- packages/li-editor/docs/common/application.ts
- packages/li-editor/docs/common/my-assets/BubbleLayer/register-form/coordinate-schema.ts
- packages/li-editor/docs/common/my-assets/BubbleLayer/register-form/index.ts
- packages/li-editor/docs/common/my-assets/BubbleLayer/register-form/schema.ts
- packages/li-editor/docs/common/my-assets/ChoroplethLayer/register-form/coordinate-schema.ts
- packages/li-editor/docs/common/my-assets/ChoroplethLayer/register-form/index.ts
- packages/li-editor/docs/common/my-assets/ChoroplethLayer/register-form/schema.ts
- packages/li-editor/docs/dev/Default/demos/application.ts
- packages/li-editor/docs/dev/Service/demos/CustomAddDataset/CustomAddDataset.less
- packages/li-editor/src/hooks/useEditorState.ts
- packages/li-editor/src/utils/dataset-parser/data-parser.ts
- packages/li-editor/src/widgets/Export/ExportData/helper.ts
- packages/li-editor/src/widgets/FiltersPanel/FiltersPanel.tsx
- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/SchemaField.tsx
- packages/li-sdk/src/utils/dataset-parser/geo-parser.ts
> fix: 检测数据集文本中的 WKT 情况

- packages/li-p2/src/components/Formily/FormCollapse/index.tsx
> chore: 属性包打包体积优化

- README.en-US.md
- README.md
> chore: docs badgen link

- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/SchemaField.tsx
> fix: 属性表单组件丢失

- bindings/pyl7vp/pyl7vp/l7vp.py
> docs: pyl7vp user guide link

- .github/workflows/lint.yml
- .github/workflows/pyl7vp-test.yml
- .github/workflows/release.yml
- bindings/pyl7vp/README.md
- bindings/pyl7vp/README.zh-CN.md
- bindings/pyl7vp/pyl7vp/l7vp.py
- bindings/pyl7vp/pyl7vp/meta.py
- bindings/pyl7vp/pyl7vp/templates/l7vp.html
- bindings/pyl7vp/setup.py
> chore: add Google Analytics

- examples/builder/src/pages/Project/index.tsx
- packages/li-editor/src/widgets/UploadDataset/UploadDataset/index.tsx
- packages/li-sdk/src/specs/metadata.ts
- packages/li-sdk/src/utils/layer.ts
- packages/li-sdk/src/utils/service.ts
- packages/li-sdk/src/utils/widget.ts
> docs: 更新文档地址

- packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/index.ts
- packages/li-analysis-assets/src/widgets/DrawControl/index.tsx
- packages/li-analysis-assets/src/widgets/LegendWidget/index.tsx
- packages/li-analysis-assets/src/widgets/LocationSearchControl/index.tsx
- packages/li-analysis-assets/src/widgets/MeasureControl/index.tsx
- packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/helper.ts
- packages/li-analysis-assets/src/widgets/MiniChart/index.tsx
- packages/li-analysis-assets/src/widgets/PropertiesPanel/index.tsx
- packages/li-analysis-assets/src/widgets/SpreadSheetTable/index.tsx
- packages/li-analysis-assets/src/widgets/TimeLine/Component/TimeLineChart/index.tsx
- packages/li-analysis-assets/src/widgets/TimeLine/Component/index.tsx
- packages/li-core-assets/src/widgets/ExportImageControl/index.tsx
- packages/li-core-assets/src/widgets/FullscreenControl/index.tsx
- packages/li-core-assets/src/widgets/GeoLocateControl/index.tsx
- packages/li-core-assets/src/widgets/LayerPopup/index.tsx
- packages/li-core-assets/src/widgets/LogoControl/index.tsx
- packages/li-core-assets/src/widgets/MapThemeControl/index.tsx
- packages/li-core-assets/src/widgets/MapViewSettingControl/index.tsx
- packages/li-core-assets/src/widgets/MouseLocationControl/index.tsx
> fix: 图表暗色主题样式问题

- packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
> fix: 长字段选择加 title 展示

- packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
- packages/li-p2/src/components/Formily/FieldSelect/Select/style.ts
>  feat: 字段选择组件支持横向滚动

- packages/li-editor/src/hooks/internal/use-immer.ts
- packages/li-editor/src/layout/RuntimeApp/index.tsx
> fix: 高德修改对象引用问题

- packages/li-editor/src/types/widget.ts
- packages/li-editor/src/widgets/DatasetsPanel/AddDataset/AddDatasetModal.tsx
- packages/li-editor/src/widgets/DatasetsPanel/AddDataset/helper.ts
- packages/li-editor/src/widgets/DatasetsPanel/AddDataset/index.tsx
- packages/li-editor/src/widgets/DatasetsPanel/DatasetList/DatasetItem/index.tsx
- packages/li-editor/src/widgets/DatasetsPanel/DatasetList/index.tsx
- packages/li-editor/src/widgets/DatasetsPanel/DatasetsPanel.tsx
- packages/li-editor/src/widgets/DatasetsPanel/ReplaceDataset/index.tsx
> feat: 编辑器支持替换数据集

- packages/li-analysis-assets/src/widgets/FilterWidget/registerForm.ts
> chore: 修改属性名称

- packages/li-editor/src/layout/index.tsx
- packages/li-editor/src/widgets/DatasetsPanel/ReplaceDataset/index.tsx
- packages/li-p2/src/components/Filter/FilterList/index.tsx
> fix: 修复替换数据集筛选器丢失

- lerna.json
- packages/li-core-assets/src/widgets/LayerPopup/ComponenStyle.ts
- packages/li-core-assets/src/widgets/LayerPopup/Component.tsx
> fix: 修复 LayerPopup 点击时无法主动关闭

- packages/li-p2/src/components/Filter/FilterItem/index.tsx
> fix: 修改筛选器遮挡问题

- packages/li-core-assets/src/layers/GridLayer/register-form/coordinate-schema.ts
- packages/li-core-assets/src/layers/HexbinLayer/register-form/coordinate-schema.ts
- packages/li-p2/src/LayerAttribute/common-schema/grid-hexbin-color-collapse.ts
> fix: 蜂窝和网格图层聚合属性问题

- packages/li-editor/package.json
- packages/li-p2/package.json
> chore: formily 升级

- packages/li-editor/src/widgets/TilesetsDataset/MVTTile/index.tsx
> chore: 修改 mvt 数据集元数据预览属性样式

- packages/li-analysis-assets/src/widgets/TimeLine/Component/index.tsx
- packages/li-analysis-assets/src/widgets/TimeLine/Component/types.ts
- packages/li-sdk/src/utils/filters/filter.ts
> refactor: 修改时间轴取筛选器数据的逻辑

- examples/builder/src/layouts/index.tsx
- packages/li-analysis-assets/src/widgets/TimeLine/Component/index.tsx
- packages/li-analysis-assets/src/widgets/TimeLine/Component/types.ts
- packages/li-p2/package.json
- packages/li-p2/src/components/Filter/FilterField/FilterDate/helper.ts
- packages/li-p2/src/components/Filter/FilterField/FilterDate/index.less
- packages/li-p2/src/components/Filter/FilterField/FilterDate/index.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterDate/type.ts
- packages/li-p2/src/components/Filter/FilterItem/constants.ts
- packages/li-p2/src/components/Filter/FilterItem/index.tsx
- packages/li-p2/src/components/Filter/types.ts
- packages/li-sdk/src/specs/dataset.ts
- packages/li-sdk/src/utils/filters/filter.ts
> feat: 数据过滤支撑时间类型筛选

- packages/li-analysis-assets/src/widgets/TimeLine/Component/TimeLineChart/index.tsx
> fix: 修复时间轴刻度问题

- examples/builder/.umirc.ts
- packages/li-editor/src/constants/base-map.ts
- packages/li-editor/src/constants/index.ts
- packages/li-editor/src/utils/application.ts
- packages/li-editor/src/utils/validator.ts
- packages/li-editor/src/widgets/MapSetting/MapSetting.tsx
- packages/li-editor/src/widgets/MapSetting/constant.tsx
> fix: 高德底图 token 失效问题

- bindings/pyl7vp/pyl7vp/meta.py
- bindings/pyl7vp/pyl7vp/templates/l7vp.html
> fix: l7vp 模版字符串

- packages/li-p2/src/components/Filter/FilterItem/index.tsx
> fix: 时间筛选器默认最小粒度格式

- packages/li-editor/src/services/editor-dataset-manager.ts
- packages/li-editor/src/utils/dataset-parser/data-parser.ts
- packages/li-editor/src/utils/validator.ts
- packages/li-sdk/src/hooks/internal/useRemoteDataset.ts
- packages/li-sdk/src/utils/dataset-parser/meta-data.ts
- packages/li-sdk/src/utils/helper.ts
> fix: 获取表格数据列头类型信息有误

- packages/li-p2/src/components/Filter/FilterField/FilterDate/index.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterNumber/NumericalInputBox.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterNumber/ValueRangeInputBox.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterNumber/index.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterString/index.tsx
- packages/li-p2/src/components/Filter/FilterItem/index.tsx
> fix：筛选框大小自定义，筛选时间问题修复

- packages/li-p2/src/components/Filter/FilterField/FilterDate/index.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterNumber/index.tsx
- packages/li-p2/src/components/Filter/FilterField/FilterString/index.tsx
- packages/li-p2/src/components/Filter/FilterItem/index.tsx
- packages/li-p2/src/components/Filter/FilterList/index.tsx
> fix: 筛选器筛选框 size 默认 middle

- packages/li-p2/src/LayerAttribute/GridLayerStyle/helper.ts
- packages/li-p2/src/LayerAttribute/HexbinLayerStyle/helper.ts
> fix: 蜂窝图层样式配置问题

- packages/li-p2/src/LayerAttribute/components/ScaleSelector/index.tsx
> fix: scale 初始填充问题

- packages/li-sdk/src/specs/dataset.ts
> fix: 栅格瓦片支持高程数据格式

- packages/li-analysis-assets/src/layers/ChinaAdminLayer/register-form/index.ts
- packages/li-analysis-assets/src/layers/FlowLayer/register-form/index.ts
- packages/li-analysis-assets/src/widgets/PropertiesPanel/registerForm.ts
- packages/li-core-assets/src/layers/ArcLayer/register-form/index.ts
- packages/li-core-assets/src/layers/BubbleLayer/register-form/index.ts
- packages/li-core-assets/src/layers/ChoroplethLayer/register-form/index.ts
- packages/li-core-assets/src/layers/GridLayer/register-form/index.ts
- packages/li-core-assets/src/layers/H3HexagonLayer/register-form/index.ts
- packages/li-core-assets/src/layers/HeatmapLayer/register-form/index.ts
- packages/li-core-assets/src/layers/HexbinLayer/register-form/index.ts
- packages/li-core-assets/src/layers/IconLayer/register-form/index.ts
- packages/li-core-assets/src/layers/LineLayer/register-form/index.ts
- packages/li-core-assets/src/widgets/LayerPopup/registerForm.ts
- packages/li-editor/src/utils/spec.ts
- packages/li-editor/src/utils/validator.ts
- packages/li-editor/src/widgets/DatasetsPanel/DatasetList/DatasetItem/index.tsx
- packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/StyleForm.tsx
- packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/index.tsx
- packages/li-editor/src/widgets/LayersPanel/LayerAttribute/index.tsx
- packages/li-editor/src/widgets/LayersPanel/helper.ts
- packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
- packages/li-p2/src/components/Formily/Slider/index.tsx
- packages/li-sdk/src/components/internal/WrapperLayer/hooks/useLayerProps.ts
- packages/li-sdk/src/specs/layer.ts
> fix: 初始化图层类型未触发更新情况

- packages/li-editor/src/widgets/FetchDataset/FetchDataset.less
- packages/li-editor/src/widgets/FetchDataset/FetchDataset.tsx
- packages/li-editor/src/widgets/FetchDataset/ProcessingFunction/helper.ts
- packages/li-editor/src/widgets/FetchDataset/ProcessingFunction/index.less
- packages/li-editor/src/widgets/FetchDataset/ProcessingFunction/index.tsx
- packages/li-editor/src/widgets/FetchDataset/helper.ts
- packages/li-editor/src/widgets/FetchDataset/types.ts
> fix: 数据处理函数

- examples/builder/src/constans/projects.ts
- packages/li-p2/src/LayerAttribute/components/IconScaleSelector/constant.ts
> chore: 添加标记图标

- packages/li-editor/src/services/editor-dataset-manager.ts
- packages/li-sdk/src/hooks/internal/useLocalDataset.ts
- packages/li-sdk/src/hooks/internal/useRemoteDataset.ts
- packages/li-sdk/src/utils/filters/filter.ts
> fix: 修复筛选器元数据信息丢失

- packages/li-analysis-assets/src/widgets/FilterControl/index.tsx
- packages/li-analysis-assets/src/widgets/FilterWidget/index.tsx
- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/index.tsx
> chore: 修改备注

- packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/Component/style.ts
- packages/li-analysis-assets/src/widgets/LegendWidget/ComponenStyle.ts
- packages/li-analysis-assets/src/widgets/LegendWidget/Component.tsx
- packages/li-analysis-assets/src/widgets/LocationSearchControl/ComponenStyle.ts
- packages/li-analysis-assets/src/widgets/VectorTilesLoaderControl/Component/style.ts
- packages/li-core-assets/src/widgets/ExportImageControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/FullscreenControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/GeoLocateControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/MapThemeControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/MapViewSettingControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/MapViewSettingControl/Component.tsx
- packages/li-core-assets/src/widgets/MouseLocationControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/ScaleControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/ZoomControl/ComponenStyle.ts
- packages/li-core-assets/src/widgets/ZoomControl/Component.tsx
> fix: 控件按钮圆角调整

- examples/builder/package.json
- examples/li-template-assets/package.json
- packages/li-analysis-assets/package.json
- packages/li-analysis-assets/src/widgets/LocationSearchControl/Component.tsx
- packages/li-core-assets/package.json
- packages/li-editor/package.json
- packages/li-p2/package.json
- packages/li-sdk/package.json
> fix: 解决位置查询密钥问题

- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/ColorPaletteGroup/index.tsx
- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/index.tsx
- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/DropDownContent.tsx
- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/index.tsx
> fix: 色带选择展示问题

- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/RangeItem/style.ts
- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/style.ts
> fix: 自定义色带遮挡问题

- packages/li-analysis-assets/src/widgets/FilterControl/Component/NumberItem.tsx
- packages/li-analysis-assets/src/widgets/FilterControl/Component/StringItem.tsx
- packages/li-analysis-assets/src/widgets/FilterControl/Component/index.tsx
- packages/li-analysis-assets/src/widgets/FilterControl/index.tsx
- packages/li-analysis-assets/src/widgets/FilterWidget/index.tsx
> fix: 数值筛选器配置态更新问题

- packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/index.tsx
- packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/index.tsx
- packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/constants.ts
- packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/helper.ts
- packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/type.ts
> feat: ResterScaleSelector 支持 linear 线性连续映射

- packages/li-analysis-assets/src/widgets/SwipeControl/Component.tsx
- packages/li-analysis-assets/src/widgets/SwipeControl/registerForm.ts
> fix: 修改设置卷帘对比控制逻辑

- packages/li-analysis-assets/src/widgets/SwipeControl/Component.tsx
- packages/li-analysis-assets/src/widgets/SwipeControl/registerForm.ts
> feat: 卷帘支持设置默认对比图层

- packages/li-analysis-assets/src/widgets/LegendWidget/ComponenStyle.ts
- packages/li-analysis-assets/src/widgets/SwipeControl/ComponenStyle.ts
> fix: 卷帘、图例控件样式问题

- packages/li-editor/src/layout/SideNav/style.ts
- packages/li-editor/src/layout/SidePanel/style.ts
- packages/li-editor/src/layout/style.ts
- packages/li-editor/src/widgets/DatasetsPanel/DatasetList/DatasetItem/style.ts
- packages/li-editor/src/widgets/DatasetsPanel/DatasetsPanelStyle.ts
- packages/li-editor/src/widgets/FiltersPanel/FilterCard/style.ts
- packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/style.ts
- packages/li-editor/src/widgets/LayersPanel/LayerList/LayerItem/style.ts
- packages/li-editor/src/widgets/LayersPanel/style.ts
- packages/li-editor/src/widgets/MapSetting/MapCenterModal/index.tsx
- packages/li-editor/src/widgets/MapSetting/MapCenterModal/style.ts
- packages/li-editor/src/widgets/WidgetsPanel/WidgetList/style.ts
- packages/li-editor/src/widgets/WidgetsPanel/WidgetsPanelStyle.ts
> style: 规范布局底色

- packages/li-editor/src/widgets/LayersPanel/LayerList/LayerItem/style.ts
- packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/style.ts
- packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/InputNumber/style.ts
- packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/style.ts
- packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/CustomItem/style.ts
- packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/UnknownItem/style.ts
- packages/li-p2/src/components/Formily/ColorPicker/style.ts
- packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/RangeItem/style.ts
> fix: antd 变量

- packages/li-analysis-assets/src/widgets/TimeLine/Component/TimeLineChart/index.tsx
- packages/li-core-assets/src/services/fetch-dataset/helper.ts
> fix: 时间轴重复多次添加筛选条件

- bindings/pyl7vp/notebooks/GeoJSON.ipynb
- bindings/pyl7vp/pyl7vp/l7vp.py
- bindings/pyl7vp/pyl7vp/meta.py
- bindings/pyl7vp/pyl7vp/templates/l7vp.html
> feat: pyl7vp 支持暗色模式

- bindings/pyl7vp/pyl7vp/config.py
- bindings/pyl7vp/pyl7vp/meta.py
- bindings/pyl7vp/pyl7vp/templates/l7vp.html
- packages/li-editor/docs/case/Theme/demos/theme.ts
> chore: 修改暗色背景色

- packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
- packages/li-p2/src/components/Formily/FieldSelect/index.tsx
- packages/li-p2/src/components/Formily/FilterConfiguration/FilterModal/FilterContent/index.tsx
> fix: 字段选择组件多选问题修复

- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/index.tsx
- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/index.tsx
> fix: 属性面板重复渲染问题

- packages/li-editor/src/services/editor-dataset-manager.ts
- packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/index.tsx
- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/index.tsx
- packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/index.tsx
> chore: 通过数据集实例获取 domain

- packages/li-analysis-assets/src/widgets/LegendWidget/helper.ts
> fix: 线图层分类数据映射图例不显示问题

- packages/li-p2/src/components/Filter/FilterField/FilterDate/index.tsx
- packages/li-p2/src/components/Formily/FilterConfiguration/components/FilterDateConfig/index.tsx
- packages/li-p2/src/components/Formily/FilterConfiguration/components/FilterStringConfig/index.tsx
> feat: 文本筛选单选时支持搜索

- examples/li-template-assets/.npmignore
- examples/li-template-assets/package.json
- packages/li-analysis-assets/.npmignore
- packages/li-analysis-assets/package.json
- packages/li-core-assets/.npmignore
- packages/li-core-assets/package.json
- packages/li-editor/.npmignore
- packages/li-editor/package.json
- packages/li-editor/src/services/editor-dataset-manager.ts
- packages/li-p2/.fatherrc.ts
- packages/li-p2/.npmignore
- packages/li-p2/package.json
- packages/li-sdk/.npmignore
- packages/li-sdk/package.json
- packages/li-sdk/src/index.ts
- packages/li-sdk/src/utils/service.ts
> fix: editor & sdk UMD 模式下依赖 query-core 版本不一致

- .github/workflows/release.yml
> ci: release dispatch

- website/package.json
> chore: 升级 L7 至最新测试版本

- .github/workflows/release.yml
> chore: custom gh page domain

- .github/workflows/lint.yml
- .github/workflows/release.yml
- packages/li-analysis-assets/package.json
- packages/li-analysis-assets/src/widgets/TimeLine/Component/TimeLineChart/index.tsx
- packages/li-p2/src/components/Formily/FilterConfiguration/FilterModal/index.tsx
- website/package.json
- website/src/constants/cases/cyberspace-pattern/index.ts
> fix: 修复时间轴把手控件

- website/package.json
> chore: update l7 version to latest

- website/src/constants/asset.ts
- website/src/constants/cases/ai-remote-sensing/index.ts
- website/src/constants/cases/zelda-app/index.ts
> chore: update cdn url

- packages/li-editor/package.json
- packages/li-editor/src/widgets/LayersPanel/LayerList/DragList/index.tsx
- https://github.com/atlassian/react-beautiful-dnd/issues/2401
> chore: replace react-beautiful-dnd with @hello-pangea/dnd
